language: node_js
node_js:
  - node
script:
  - yarn run build
  - yarn run lint
  - yarn run lint-examples
  - yarn run test:cover
  - yarn run test-types
  - yarn run bundlesize
after_success: yarn run coveralls
cache: yarn
# addons:
#   apt:
#     sources:
#     - ubuntu-toolchain-r-test
#     packages:
#     - g++-4.8
# env:
#   - CXX=g++-4.8

